"""add bank role to user model

Revision ID: 03c096fd0341
Revises: 31cf3da2255
Create Date: 2025-10-23 15:15:56.656876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03c096fd0341'
down_revision: Union[str, None] = '31cf3da2255'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add 'bank' value to the userrole enum
    op.execute("ALTER TYPE userrole ADD VALUE 'bank'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: PostgreSQL doesn't support removing enum values directly
    # This would require recreating the enum type and updating all references
    # For now, we'll leave the 'bank' value in the enum
    pass
    # ### end Alembic commands ###
