"""Add simulated field to Case

Revision ID: 20fdcf3b7f11
Revises: 3bdf1bd0b4b6
Create Date: 2025-02-04 17:46:03.646951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20fdcf3b7f11'
down_revision: Union[str, None] = '3bdf1bd0b4b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case', sa.Column('simulated', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case', 'simulated')
    # ### end Alembic commands ###
