"""increase_column_sizes_for_pjud_folios

Revision ID: 2705da507b9c
Revises: 3f98f03b5fdf
Create Date: 2025-09-11 22:47:00.642697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2705da507b9c'
down_revision: Union[str, None] = '3f98f03b5fdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pjud_folios', 'fec_tramite',
                    existing_type=sa.VARCHAR(length=20),
                    type_=sa.VARCHAR(length=50),
                    existing_nullable=True)
    op.alter_column('pjud_folios', 'tramite',
                    existing_type=sa.VARCHAR(length=100),
                    type_=sa.VARCHAR(length=200),
                    existing_nullable=True)
    op.alter_column('pjud_folios', 'etapa',
                    existing_type=sa.VARCHAR(length=100),
                    type_=sa.VARCHAR(length=200),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pjud_folios', 'etapa',
                    existing_type=sa.VARCHAR(length=200),
                    type_=sa.VARCHAR(length=100),
                    existing_nullable=True)
    op.alter_column('pjud_folios', 'tramite',
                    existing_type=sa.VARCHAR(length=200),
                    type_=sa.VARCHAR(length=100),
                    existing_nullable=True)
    op.alter_column('pjud_folios', 'fec_tramite',
                    existing_type=sa.VARCHAR(length=50),
                    type_=sa.VARCHAR(length=20),
                    existing_nullable=True)
    # ### end Alembic commands ###
