"""Adjust caseevent constrain

Revision ID: 2f95d21cba23
Revises: d6641e0dba9a
Create Date: 2024-12-04 20:48:32.684179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f95d21cba23'
down_revision: Union[str, None] = 'd6641e0dba9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('caseevent_next_event_id_fkey', 'caseevent', type_='foreignkey')
    op.create_foreign_key(None, 'caseevent', 'caseevent', ['next_event_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'caseevent', type_='foreignkey')
    op.create_foreign_key('caseevent_next_event_id_fkey', 'caseevent', 'caseevent', ['next_event_id'], ['id'])
    # ### end Alembic commands ###
