"""Add generated field to Document

Revision ID: 3bdf1bd0b4b6
Revises: f8e8a42d95ab
Create Date: 2025-02-03 23:42:22.190017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bdf1bd0b4b6'
down_revision: Union[str, None] = 'f8e8a42d95ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('generated', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'generated')
    # ### end Alembic commands ###
