"""create_pjud_folios_table

Revision ID: 3f98f03b5fdf
Revises: 80a613e95a3c
Create Date: 2025-09-11 22:41:26.186364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f98f03b5fdf'
down_revision: Union[str, None] = '80a613e95a3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pjud_folios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folio', sa.String(length=50), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('year', sa.String(length=4), nullable=False),
    sa.Column('doc', sa.String(length=50), nullable=True),
    sa.Column('anexo', sa.Text(), nullable=True),
    sa.Column('etapa', sa.String(length=100), nullable=True),
    sa.Column('tramite', sa.String(length=100), nullable=True),
    sa.Column('desc_tramite', sa.Text(), nullable=True),
    sa.Column('fec_tramite', sa.String(length=20), nullable=True),
    sa.Column('foja', sa.String(length=20), nullable=True),
    sa.Column('georref', sa.String(length=50), nullable=True),
    sa.Column('hito', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('scraping_session_id', sa.String(length=100), nullable=False),
    sa.Column('scraping_type', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('folio', 'rol', 'year', name='uq_folio_rol_year')
    )
    op.create_index(op.f('ix_pjud_folios_folio'), 'pjud_folios', ['folio'], unique=False)
    op.create_index(op.f('ix_pjud_folios_rol'), 'pjud_folios', ['rol'], unique=False)
    op.create_index(op.f('ix_pjud_folios_scraping_session_id'), 'pjud_folios', ['scraping_session_id'], unique=False)
    op.create_index(op.f('ix_pjud_folios_year'), 'pjud_folios', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pjud_folios_year'), table_name='pjud_folios')
    op.drop_index(op.f('ix_pjud_folios_scraping_session_id'), table_name='pjud_folios')
    op.drop_index(op.f('ix_pjud_folios_rol'), table_name='pjud_folios')
    op.drop_index(op.f('ix_pjud_folios_folio'), table_name='pjud_folios')
    op.drop_table('pjud_folios')
    # ### end Alembic commands ###
