"""add_case_recepthor_id_to_case

Revision ID: 4682a2444df1
Revises: 7bb4a51adaf7
Create Date: 2025-09-12 12:48:05.439719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4682a2444df1'
down_revision: Union[str, None] = '7bb4a51adaf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case', sa.Column('case_recepthor_id', sa.Uuid(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case', 'case_recepthor_id')
    # ### end Alembic commands ###
