"""Add DISPATCH_START to CaseEventType enum

Revision ID: 6da0b1c07fd3
Revises: d6bb0416bcc7
Create Date: 2025-09-11 16:39:20.823201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6da0b1c07fd3'
down_revision: Union[str, None] = 'd6bb0416bcc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE caseeventtype ADD VALUE 'dispatch_start'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
