"""Add duration column to CaseStats

Revision ID: 762e6afacef1
Revises: 3ac7d4c57ff4
Create Date: 2025-04-02 15:22:10.357883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '762e6afacef1'
down_revision: Union[str, None] = '3ac7d4c57ff4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('casestats', sa.Column('duration', sa.Integer(), nullable=True))
    op.execute(
        """
        CREATE OR REPLACE FUNCTION update_case_duration() 
        RETURNS TRIGGER AS $$
        DECLARE
            new_duration INTEGER;
            cs_id uuid;
        BEGIN
            -- Get the associated case_stats id from the event row.
            cs_id := COALESCE(NEW.case_stats_id, OLD.case_stats_id);
            
            -- Calculate duration in days using the earliest and latest event dates.
            SELECT (MAX(creation_date) - MIN(creation_date))
            INTO new_duration
            FROM casestatsevent
            WHERE case_stats_id = cs_id;
            
            -- Update the corresponding case_stats row.
            UPDATE casestats
            SET duration = new_duration
            WHERE id = cs_id;
            
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_update_case_duration
        AFTER INSERT OR UPDATE OR DELETE ON casestatsevent
        FOR EACH ROW
        EXECUTE FUNCTION update_case_duration();
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS trg_update_case_duration ON casestatsevent")
    op.execute("DROP FUNCTION IF EXISTS update_case_duration()")
    op.drop_column('casestats', 'duration')
    # ### end Alembic commands ###
