"""add_user_law_firm_relationship

Revision ID: 7e9c79876662
Revises: f6f4e685d93e
Create Date: 2025-10-17 16:29:01.847329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e9c79876662'
down_revision: Union[str, None] = 'f6f4e685d93e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('law_firm_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'user', 'lawfirm', ['law_firm_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'law_firm_id')
    # ### end Alembic commands ###
