"""add_unique_constraint_to_pjud_folio

Revision ID: 80a613e95a3c
Revises: c598b846e1b4
Create Date: 2025-09-11 15:26:00.103597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80a613e95a3c'
down_revision: Union[str, None] = 'c598b846e1b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
