"""Add simulated field to Litigant and Document models

Revision ID: 90dbd505cbe2
Revises: 2f95d21cba23
Create Date: 2024-12-05 18:51:09.174311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90dbd505cbe2'
down_revision: Union[str, None] = '2f95d21cba23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('simulated', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('litigant', sa.Column('simulated', sa.Boolean(), nullable=False, server_default=sa.text('false')))

    op.execute('UPDATE document SET simulated = FALSE')
    op.execute('UPDATE litigant SET simulated = FALSE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('litigant', 'simulated')
    op.drop_column('document', 'simulated')
    # ### end Alembic commands ###
