"""Add amount and currency to Case

Revision ID: 94d51e489b48
Revises: 762e6afacef1
Create Date: 2025-04-03 02:05:13.773211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94d51e489b48'
down_revision: Union[str, None] = '762e6afacef1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case', sa.Column('amount', sa.Float(), nullable=True))
    op.add_column('case', sa.Column('amount_currency', sa.Enum('CLP', 'USD', 'UF', name='currencytype'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case', 'amount_currency')
    op.drop_column('case', 'amount')
    # ### end Alembic commands ###
