"""Add CaseEventSuggestion model

Revision ID: 95fc8b2ce5f8
Revises: 7f5a33dd085b
Create Date: 2024-12-11 00:11:30.728609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95fc8b2ce5f8'
down_revision: Union[str, None] = '7f5a33dd085b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
