"""add_receptor_and_receptor_detail_tables

Revision ID: af39c99359bf
Revises: d8fcfb9708fa
Create Date: 2025-10-15 12:35:02.870630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af39c99359bf'
down_revision: Union[str, None] = 'd8fcfb9708fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receptor',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recepthor_external_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('primary_email', sa.String(length=255), nullable=True),
    sa.Column('secondary_email', sa.String(length=255), nullable=True),
    sa.Column('primary_phone', sa.String(length=50), nullable=True),
    sa.Column('secondary_phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('receptordetail',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('receptor_id', sa.Uuid(), nullable=False),
    sa.Column('tribunal_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['receptor_id'], ['receptor.id'], ),
    sa.ForeignKeyConstraint(['tribunal_id'], ['tribunal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('receptordetail')
    op.drop_table('receptor')
    # ### end Alembic commands ###
