"""Add withdrawal suggestiontype

Revision ID: c50cd253d113
Revises: e26df8b9aea0
Create Date: 2025-04-07 19:45:16.038683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c50cd253d113'
down_revision: Union[str, None] = 'e26df8b9aea0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE suggestiontype ADD VALUE 'WITHDRAWAL'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE suggestiontype_new AS ENUM ('DEMAND_TEXT_CORRECTION', 'EXCEPTIONS_RESPONSE', 'RESPONSE', 'REQUEST', 'COMPROMISE', 'OTHER')")
    op.execute("ALTER TABLE caseeventsuggestion ALTER COLUMN type TYPE suggestiontype_new USING type::text::suggestiontype_new")
    op.execute("DROP TYPE suggestiontype")
    op.execute("ALTER TYPE suggestiontype_new RENAME TO suggestiontype")
    # ### end Alembic commands ###
