"""add_rol_and_year_to_pjud_folio

Revision ID: c598b846e1b4
Revises: 4610ecb33c48
Create Date: 2025-09-11 11:53:22.858868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c598b846e1b4'
down_revision: Union[str, None] = '4610ecb33c48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
