"""Add CaseDetail, Tribunal and Court models

Revision ID: d6bb0416bcc7
Revises: 4610ecb33c48
Create Date: 2025-09-11 11:28:18.478030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd6bb0416bcc7'
down_revision: Union[str, None] = '4610ecb33c48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('court',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recepthor_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tribunal',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recepthor_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('casedetail',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('court_id', sa.Uuid(), nullable=False),
    sa.Column('tribunal_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['court_id'], ['court.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tribunal_id'], ['tribunal.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('casedetail')
    op.drop_table('tribunal')
    op.drop_table('court')
    # ### end Alembic commands ###
