"""add_actions_table

Revision ID: d8fcfb9708fa
Revises: 7d660a63cbe0
Create Date: 2025-09-26 15:05:49.876251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

revision: str = 'd8fcfb9708fa'
down_revision: Union[str, None] = '7d660a63cbe0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table('action',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('action_to_follow', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('responsible', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_pjud_folios_folio', table_name='pjud_folios')
    op.drop_index('ix_pjud_folios_rol', table_name='pjud_folios')
    op.drop_index('ix_pjud_folios_scraping_session_id', table_name='pjud_folios')
    op.drop_index('ix_pjud_folios_year', table_name='pjud_folios')
    op.drop_table('pjud_folios')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pjud_folios',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('folio_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('case_number', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('document', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('stage', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('procedure', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('procedure_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('procedure_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('page', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('milestone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('scraping_session_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('scraping_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pjud_folios_pkey'),
    sa.UniqueConstraint('folio_number', 'case_number', 'year', 'procedure_description', name='uq_folio_case_year_description')
    )
    op.create_index('ix_pjud_folios_year', 'pjud_folios', ['year'], unique=False)
    op.create_index('ix_pjud_folios_scraping_session_id', 'pjud_folios', ['scraping_session_id'], unique=False)
    op.create_index('ix_pjud_folios_rol', 'pjud_folios', ['case_number'], unique=False)
    op.create_index('ix_pjud_folios_folio', 'pjud_folios', ['folio_number'], unique=False)
    op.drop_table('action')
    # ### end Alembic commands ###
