"""Add more caseeventtype values

Revision ID: e26df8b9aea0
Revises: 94d51e489b48
Create Date: 2025-04-03 20:50:41.050155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e26df8b9aea0'
down_revision: Union[str, None] = '94d51e489b48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE caseeventtype ADD VALUE 'SENTENCE'")
    op.execute("ALTER TYPE caseeventtype ADD VALUE 'ASSET_SEIZURE_ORDER'")
    op.execute("ALTER TYPE caseeventtype ADD VALUE 'WITHDRAWAL'")
    op.execute("ALTER TYPE documenttype ADD VALUE 'SENTENCE'")
    op.execute("ALTER TYPE documenttype ADD VALUE 'ASSET_SEIZURE_ORDER'")
    op.execute("ALTER TYPE documenttype ADD VALUE 'WITHDRAWAL'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE caseeventtype_new AS ENUM ('DEMAND_START', 'EXCEPTIONS', 'DISPATCH_RESOLUTION', 'RESOLUTION', 'EXCEPTIONS_RESPONSE', 'REQUEST', 'OTHER', 'RESPONSE', 'DEMAND_TEXT_CORRECTION', 'COMPROMISE')")
    op.execute("ALTER TABLE caseevent ALTER COLUMN type TYPE caseeventtype_new USING type::text::caseeventtype_new")
    op.execute("DROP TYPE caseeventtype")
    op.execute("ALTER TYPE caseeventtype_new RENAME TO caseeventtype")

    op.execute("CREATE TYPE documenttype_new AS ENUM ('DEMAND_TEXT', 'EXCEPTIONS', 'DISPATCH_RESOLUTION', 'RESOLUTION', 'EXCEPTIONS_RESPONSE', 'REQUEST', 'OTHER', 'RESPONSE', 'DEMAND_TEXT_CORRECTION', 'COMPROMISE')")
    op.execute("ALTER TABLE document ALTER COLUMN type TYPE documenttype_new USING type::text::documenttype_new")
    op.execute("DROP TYPE documenttype")
    op.execute("ALTER TYPE documenttype_new RENAME TO documenttype")
    # ### end Alembic commands ###
