"""add_law_firm_table

Revision ID: f6f4e685d93e
Revises: f8a601c605e4
Create Date: 2025-10-17 15:45:14.246838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f6f4e685d93e'
down_revision: Union[str, None] = 'f8a601c605e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add new columns as nullable first
    op.add_column('lawfirm', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('lawfirm', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    
    # Step 2: Copy data from old columns to new columns
    op.execute('UPDATE lawfirm SET name = nombre, description = descripcion')
    
    # Step 3: Make 'name' column NOT NULL
    op.alter_column('lawfirm', 'name', nullable=False)
    
    # Step 4: Drop old columns
    op.drop_column('lawfirm', 'nombre')
    op.drop_column('lawfirm', 'descripcion')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add old columns back
    op.add_column('lawfirm', sa.Column('descripcion', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('lawfirm', sa.Column('nombre', sa.VARCHAR(), autoincrement=False, nullable=True))
    
    # Step 2: Copy data back
    op.execute('UPDATE lawfirm SET nombre = name, descripcion = description')
    
    # Step 3: Make 'nombre' column NOT NULL
    op.alter_column('lawfirm', 'nombre', nullable=False)
    
    # Step 4: Drop new columns
    op.drop_column('lawfirm', 'description')
    op.drop_column('lawfirm', 'name')
    # ### end Alembic commands ###
