"""Add more event and document types

Revision ID: f8e8a42d95ab
Revises: 95fc8b2ce5f8
Create Date: 2025-01-09 03:10:38.845307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8e8a42d95ab'
down_revision: Union[str, None] = '95fc8b2ce5f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE caseeventtype ADD VALUE 'RESPONSE'")
    op.execute("ALTER TYPE caseeventtype ADD VALUE 'DEMAND_TEXT_CORRECTION'")
    op.execute("ALTER TYPE caseeventtype ADD VALUE 'COMPROMISE'")
    op.execute("ALTER TYPE documenttype ADD VALUE 'RESPONSE'")
    op.execute("ALTER TYPE documenttype ADD VALUE 'DEMAND_TEXT_CORRECTION'")
    op.execute("ALTER TYPE documenttype ADD VALUE 'COMPROMISE'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE caseeventtype_new AS ENUM ('DEMAND_START', 'EXCEPTIONS', 'DISPATCH_RESOLUTION', 'RESOLUTION', 'EXCEPTIONS_RESPONSE', 'REQUEST', 'OTHER')")
    op.execute("ALTER TABLE caseevent ALTER COLUMN type TYPE caseeventtype_new USING type::text::caseeventtype_new")
    op.execute("DROP TYPE caseeventtype")
    op.execute("ALTER TYPE caseeventtype_new RENAME TO caseeventtype")

    op.execute("CREATE TYPE documenttype_new AS ENUM ('DEMAND_TEXT', 'EXCEPTIONS', 'DISPATCH_RESOLUTION', 'RESOLUTION', 'EXCEPTIONS_RESPONSE', 'REQUEST', 'OTHER')")
    op.execute("ALTER TABLE document ALTER COLUMN type TYPE documenttype_new USING type::text::documenttype_new")
    op.execute("DROP TYPE documenttype")
    op.execute("ALTER TYPE documenttype_new RENAME TO documenttype")
    # ### end Alembic commands ###
