from enum import Enum
from datetime import datetime
from typing import Any, TYPE_CHECKING

from sqlalchemy import Column, DateTime, Enum as SQLAlchemyEnum, ForeignKey, JSON
from sqlalchemy.sql import func
from sqlmodel import Field, SQLModel, Relationship
from uuid import UUID, uuid4

from models.pydantic import DocumentType
from .litigant import Litigant


if TYPE_CHECKING:
    from .case import CaseEvent


class Document(SQLModel, table=True):
    id: UUID = Field(default_factory=uuid4, primary_key=True)
    author_id: UUID | None = Field(
        None,
        foreign_key="litigant.id",
        nullable=True,
        description="Litigant ID",
    )
    author: Litigant = Relationship(
        back_populates="documents",
        sa_relationship=ForeignKey("litigant.id"),
    )
    name: str = Field(..., description="Document name")
    type: DocumentType = Field(
        default=DocumentType.OTHER,
        sa_column=Column(SQLAlchemyEnum(DocumentType), nullable=False),
        description="Document type",
    )
    case_event_id: UUID | None = Field(
        None,
        ondelete="CASCADE",
        foreign_key="caseevent.id",
        nullable=True,
        description="CaseEvent ID",
    )
    case_event: "CaseEvent" = Relationship(
        back_populates="documents",
        sa_relationship=ForeignKey("caseevent.id"),
    )
    storage_key: str | None = Field(None, description="Unique key to access the stored file")
    content: dict[str, Any] | None = Field(
        sa_column=Column(JSON), 
        description="Document content as JSON",
    )
    created_at: datetime = Field(
        sa_column=Column(DateTime(timezone=True), server_default=func.now()),
        description="Document creation time",
    )
    updated_at: datetime = Field(
        sa_column=Column(DateTime(timezone=True), onupdate=func.now(), default=func.now()),
        description="Document last update time",
    )
    generated: bool = Field(False, description="True if the document was generated by the system, false if external")
    simulated: bool = Field(False, description="Whether the document is simulated or not")
