"""Allow null court_number

Revision ID: 3ac7d4c57ff4
Revises: c1300267fcff
Create Date: 2025-03-18 23:46:20.533815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ac7d4c57ff4'
down_revision: Union[str, None] = 'c1300267fcff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('casestats', 'court_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('casestats', 'court_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
