"""Add is_co_debtor to Litigant

Revision ID: 4610ecb33c48
Revises: c50cd253d113
Create Date: 2025-04-07 20:15:02.521548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4610ecb33c48'
down_revision: Union[str, None] = 'c50cd253d113'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('litigant', sa.Column('is_co_debtor', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('litigant', 'is_co_debtor')
    # ### end Alembic commands ###
