"""Add CaseStats

Revision ID: c1300267fcff
Revises: 20fdcf3b7f11
Create Date: 2025-03-17 21:22:53.397175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1300267fcff'
down_revision: Union[str, None] = '20fdcf3b7f11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('casestats',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('bank', sa.String(), nullable=False),
    sa.Column('court_number', sa.Integer(), nullable=False),
    sa.Column('court_city', sa.String(), nullable=False),
    sa.Column('case_role', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('case_type', sa.String(), nullable=False),
    sa.Column('legal_stage', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('casestatsevent',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_stats_id', sa.Uuid(), nullable=False),
    sa.Column('creation_date', sa.Date(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('enumeration', sa.String(), nullable=True),
    sa.Column('page_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['case_stats_id'], ['casestats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('casestatsevent')
    op.drop_table('casestats')
    # ### end Alembic commands ###
