from .generator import DemandTextAdditionalRequestGenerator
from .models import DemandTextAdditionalRequestGeneratorInput, DemandTextAdditionalRequestGeneratorOutput, DemandTextAdditionalRequestStructure
